<a href="https://colab.research.google.com/github/NgyThuw/Algorithms_Analysis/blob/main/Week_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:
url = "https://raw.githubusercontent.com/huynhhoc/DataAnalystDeepLearning/refs/heads/main/Data/heart_disease_dataset.csv"

df = pd.read_csv(url)

df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,state
0,63.0,M,tap,145.0,233.0,yes,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0.0
1,67.0,M,asp,160.0,286.0,no,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2.0
2,67.0,M,asp,120.0,229.0,no,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1.0
3,37.0,M,nap,130.0,250.0,no,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0.0
4,41.0,F,aap,130.0,204.0,no,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0.0

In [3]:
print("Shape:", df.shape)

df.info()

df.describe()

Shape: (303, 14)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       295 non-null    float64
 1   sex       295 non-null    object
 2   cp        292 non-null    object
 3   trestbps  295 non-null    float64
 4   chol      293 non-null    float64
 5   fbs       295 non-null    object
 6   restecg   295 non-null    float64
 7   thalach   291 non-null    float64
 8   exang     295 non-null    float64
 9   oldpeak   295 non-null    float64
 10  slope     295 non-null    float64
 11  ca        291 non-null    float64
 12  thal      295 non-null    float64
 13  state     293 non-null    float64
dtypes: float64(11), object(3)
memory usage: 33.3+ KB

,age,trestbps,chol,restecg,thalach,exang,oldpeak,slope,ca,thal,state
count,295.000000,295.000000,293.000000,295.000000,291.000000,295.000000,295.000000,295.000000,291.000000,295.000000,293.000000
mean,54.362712,131.389831,247.225256,1.003390,150.054983,0.318644,1.038644,1.589831,0.656357,4.671186,0.928328
std,9.040007,17.271361,51.819006,0.994879,22.684882,0.466742,1.170266,0.615474,0.931509,1.968377,1.229621
min,29.000000,94.000000,126.000000,0.000000,71.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,47.500000,120.000000,211.000000,0.000000,136.500000,0.000000,0.000000,1.000000,0.000000,3.000000,0.000000
50%,55.000000,130.000000,242.000000,1.000000,153.000000,0.000000,0.700000,2.000000,0.000000,3.000000,0.000000
75%,61.000000,140.000000,276.000000,2.000000,166.000000,1.000000,1.600000,2.000000,1.000000,7.000000,2.000000
max,77.000000,200.000000,564.000000,2.000000,202.000000,1.000000,6.200000,3.000000,3.000000,7.000000,4.000000

In [5]:
df.isnull().sum()
df = df.dropna()
df.fillna(df.median(numeric_only=True), inplace=True)

In [6]:
print("Before:", df.shape)

df = df.drop_duplicates()

print("After:", df.shape)

Before: (284, 14)
After: (284, 14)

In [8]:
target_col = df.columns[-1]

print("Target column:", target_col)

X = df.iloc[:, :-1]
y = df.iloc[:, -1]

print("X shape:", X.shape)
print("y shape:", y.shape)

Target column: state
X shape: (284, 13)
y shape: (284,)

In [14]:
print(X.dtypes)

categorical_cols = X.select_dtypes(include=['object']).columns.tolist()

numerical_cols = X.select_dtypes(exclude=['object']).columns.tolist()

print("Categorical Columns:")
print(categorical_cols)

print()

print("Numerical Columns:")
print(numerical_cols)

age         float64
sex          object
cp           object
trestbps    float64
chol        float64
fbs          object
restecg     float64
thalach     float64
exang       float64
oldpeak     float64
slope       float64
ca          float64
thal        float64
dtype: object
Categorical Columns:
['sex', 'cp', 'fbs']

Numerical Columns:
['age', 'trestbps', 'chol', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal']

In [16]:
from sklearn.preprocessing import LabelEncoder

label_encoders = {}

for col in categorical_cols:
    le = LabelEncoder()

    X[col] = le.fit_transform(X[col])

    label_encoders[col] = le

In [21]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Train:", X_train.shape)
print("Test :", X_test.shape)

Train: (227, 13)
Test : (57, 13)

In [18]:
X_train, X_val, y_train, y_val = train_test_split(
    X_train,
    y_train,
    test_size=0.2,
    random_state=42,
    stratify=y_train
)

print("Train:", X_train.shape)
print("Validation:", X_val.shape)
print("Test:", X_test.shape)

Train: (181, 13)
Validation: (46, 13)
Test: (57, 13)

In [20]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_val = scaler.transform(X_val)

X_test = scaler.transform(X_test)

In [23]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense

model = Sequential([

    Input(shape=(X_train.shape[1],)),

    Dense(32, activation='relu'),

    Dense(16, activation='relu'),

    Dense(8, activation='relu'),

    Dense(1, activation='sigmoid')
])

In [24]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [25]:
history = model.fit(
    X_train,
    y_train,
    validation_data=(X_val, y_val),
    epochs=50,
    batch_size=32,
    verbose=1
)

Epoch 1/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - accuracy: 0.3084 - loss: 0.2372 - val_accuracy: 0.3043 - val_loss: 0.5774
Epoch 2/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.1850 - loss: -0.1313 - val_accuracy: 0.3261 - val_loss: 0.5654
Epoch 3/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.1850 - loss: -0.4759 - val_accuracy: 0.3913 - val_loss: 0.5644
Epoch 4/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.1850 - loss: -0.9599 - val_accuracy: 0.4130 - val_loss: 0.5564
Epoch 5/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.2070 - loss: -1.5588 - val_accuracy: 0.4348 - val_loss: 0.5584
Epoch 6/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.2599 - loss: -2.0095 - val_accuracy: 0.4348 - val_loss: 0.5480
Epoch 7/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.2775 - loss: -2.2725 - val_accuracy: 0.4565 - val_loss: 0.5328
Epoch 8/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.2952 - loss: -2.5128 - val_accuracy: 0.4565 - val_loss: 0.5204
Epoch 9/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.2996 - loss: -2.7713 - val_accuracy: 0.4565 - val_loss: 0.5028
Epoch 10/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.2687 - loss: -3.1197 - val_accuracy: 0.4565 - val_loss: 0.4846
Epoch 11/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.2467 - loss: -3.4462 - val_accuracy: 0.4565 - val_loss: 0.4646
Epoch 12/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3084 - loss: -3.7400 - val_accuracy: 0.5217 - val_loss: 0.4561
Epoch 13/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3833 - loss: -3.5794 - val_accuracy: 0.5000 - val_loss: 0.4314
Epoch 14/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.2335 - loss: -4.2409 - val_accuracy: 0.5000 - val_loss: 0.3856
Epoch 15/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.1982 - loss: -4.4995 - val_accuracy: 0.5652 - val_loss: 0.3503
Epoch 16/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.2555 - loss: -5.2272 - val_accuracy: 0.5652 - val_loss: 0.3205
Epoch 17/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3744 - loss: -5.0301 - val_accuracy: 0.5652 - val_loss: 0.2925
Epoch 18/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3524 - loss: -5.7369 - val_accuracy: 0.5870 - val_loss: 0.2503
Epoch 19/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3216 - loss: -6.3317 - val_accuracy: 0.5652 - val_loss: 0.2200
Epoch 20/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.2996 - loss: -6.8628 - val_accuracy: 0.5435 - val_loss: 0.1721
Epoch 21/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.2070 - loss: -7.0016 - val_accuracy: 0.5435 - val_loss: 0.1054
Epoch 22/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.1894 - loss: -7.2244 - val_accuracy: 0.5652 - val_loss: 0.0409
Epoch 23/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.1982 - loss: -8.0694 - val_accuracy: 0.5652 - val_loss: -0.0170
Epoch 24/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.2863 - loss: -9.8689 - val_accuracy: 0.5870 - val_loss: -0.0694
Epoch 25/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3304 - loss: -10.7537 - val_accuracy: 0.5870 - val_loss: -0.1499
Epoch 26/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.3568 - loss: -11.3034 - val_accuracy: 0.5870 - val_loss: -0.2221
Epoch 27/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.2291 - loss: -11.3912 - val_accuracy: 0.5652 - val_loss: -0.3739
Epoch 28/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.1894 - loss: -12.9683 - val_accuracy: 0.6087 - val_loss: -0.4565
Epoch 29/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.3260 - loss: -14.4850 - val_accuracy: 0.5870 - val_loss: -0.5034
Epoch 30/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3568 - loss: -15.5174 - val_accuracy: 0.5870 - val_loss: -0.6078
Epoch 31/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3260 - loss: -17.7370 - val_accuracy: 0.5870 - val_loss: -0.6768
Epoch 32/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.2996 - loss: -19.0991 - val_accuracy: 0.5870 - val_loss: -0.7796
Epoch 33/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3612 - loss: -18.8768 - val_accuracy: 0.5870 - val_loss: -0.8555
Epoch 34/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3348 - loss: -22.5163 - val_accuracy: 0.5870 - val_loss: -1.0229
Epoch 35/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.2026 - loss: -20.9315 - val_accuracy: 0.5870 - val_loss: -1.2021
Epoch 36/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.2379 - loss: -24.6932 - val_accuracy: 0.5870 - val_loss: -1.2697
Epoch 37/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.3436 - loss: -26.6897 - val_accuracy: 0.5870 - val_loss: -1.4120
Epoch 38/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.3172 - loss: -29.8673 - val_accuracy: 0.5870 - val_loss: -1.5646
Epoch 39/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.2996 - loss: -31.8195 - val_accuracy: 0.5870 - val_loss: -1.7433
Epoch 40/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.2952 - loss: -34.6421 - val_accuracy: 0.5870 - val_loss: -1.9357
Epoch 41/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.2599 - loss: -36.9505 - val_accuracy: 0.5870 - val_loss: -2.1252
Epoch 42/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.2687 - loss: -40.3299 - val_accuracy: 0.5870 - val_loss: -2.2643
Epoch 43/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.4097 - loss: -35.7375 - val_accuracy: 0.5870 - val_loss: -2.3681
Epoch 44/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.3040 - loss: -44.3977 - val_accuracy: 0.5870 - val_loss: -2.7049
Epoch 45/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.1982 - loss: -39.5161 - val_accuracy: 0.5652 - val_loss: -3.0019
Epoch 46/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.2026 - loss: -48.2193 - val_accuracy: 0.5870 - val_loss: -3.1720
Epoch 47/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.3656 - loss: -50.9093 - val_accuracy: 0.6087 - val_loss: -3.3333
Epoch 48/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.2996 - loss: -53.2291 - val_accuracy: 0.5652 - val_loss: -3.8182
Epoch 49/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.1982 - loss: -56.1369 - val_accuracy: 0.5652 - val_loss: -4.1809
Epoch 50/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.2335 - loss: -67.5238 - val_accuracy: 0.6087 - val_loss: -4.3651

In [26]:
loss, acc = model.evaluate(
    X_test,
    y_test
)

print("Accuracy:", acc)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.3509 - loss: -62.5269
Accuracy: 0.35087719559669495

In [27]:
y_pred = model.predict(X_test)

y_pred = (y_pred > 0.5).astype(int)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 204ms/step

In [28]:
cm = confusion_matrix(
    y_test,
    y_pred
)

print(cm)

[[10 21  0  0  0]
 [ 0 10  0  0  0]
 [ 0  7  0  0  0]
 [ 0  6  0  0  0]
 [ 0  3  0  0  0]]

In [29]:
print(
    classification_report(
        y_test,
        y_pred
    )
)

              precision    recall  f1-score   support

         0.0       1.00      0.32      0.49        31
         1.0       0.21      1.00      0.35        10
         2.0       0.00      0.00      0.00         7
         3.0       0.00      0.00      0.00         6
         4.0       0.00      0.00      0.00         3

    accuracy                           0.35        57
   macro avg       0.24      0.26      0.17        57
weighted avg       0.58      0.35      0.33        57

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))